Ensure DateFiltering is included in models
workarea-commerce/workarea-api pull request #15
Opened 2020-01-31 20:11 UTC by tubbo

To avoid a missing `by_updated_at` method error in tests, explicitly
`decorate` the models that may autoload `ApplicationDocument` prior to
the API's engine initializer getting called.

**NOTE:** This change should be more apparent in mega-build or an actual
app, since the tests don't fail when running locally.

2020-02-04 14:43 UTC, mttdffy approved these changes
Any reason not to decorate both in a single decorator? Maybe even just putting it in the DateFiltering file?

2020-02-04 16:54 UTC, bencrouse commented
So the actual issue is that any model loaded during initialization isn't going to receive this decoration. Here was the original fix in base: https://github.com/workarea-commerce/workarea/commit/5b0663628480533a78298ebd06ee37fec5a2e8aa

2020-02-04 16:54 UTC, bencrouse requested changes
See my above comment

2020-02-04 17:04 UTC, tubbo commented
@bencrouse so can this be backported to v3.4+ or is there something in there that's 3.5 specific?

2020-02-05 16:09 UTC, bencrouse commented
I don't believe this could be backported. I remember thinking the API-change was the only way I could think of to fix it, so it would have to be fixed in v3.5.

2020-02-13 22:17 UTC, closed without merging